/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/MDIApplication.java to edit this template
 */
package FRONTEND_;

/**
 *
 * @author RGH-LS24-07
 */
public class DB extends javax.swing.JFrame {

    /**
     * Creates new form DB
     */
    public DB() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        desktopPane = new javax.swing.JDesktopPane();
        menu = new javax.swing.JTabbedPane();
        pantalones = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jScrollPane5 = new javax.swing.JScrollPane();
        jTextPane5 = new javax.swing.JTextPane();
        jLabel6 = new javax.swing.JLabel();
        jScrollPane6 = new javax.swing.JScrollPane();
        jTextPane6 = new javax.swing.JTextPane();
        jLabel7 = new javax.swing.JLabel();
        jScrollPane7 = new javax.swing.JScrollPane();
        jTextPane7 = new javax.swing.JTextPane();
        jLabel8 = new javax.swing.JLabel();
        jScrollPane8 = new javax.swing.JScrollPane();
        jTextPane8 = new javax.swing.JTextPane();
        jLabel23 = new javax.swing.JLabel();
        jScrollPane23 = new javax.swing.JScrollPane();
        jTextPane23 = new javax.swing.JTextPane();
        jScrollPane24 = new javax.swing.JScrollPane();
        jTextPane24 = new javax.swing.JTextPane();
        jScrollPane25 = new javax.swing.JScrollPane();
        jTextPane25 = new javax.swing.JTextPane();
        jScrollPane26 = new javax.swing.JScrollPane();
        jTextPane26 = new javax.swing.JTextPane();
        jScrollPane27 = new javax.swing.JScrollPane();
        jTextPane27 = new javax.swing.JTextPane();
        jScrollPane28 = new javax.swing.JScrollPane();
        jTextPane28 = new javax.swing.JTextPane();
        jLabel24 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        jLabel29 = new javax.swing.JLabel();
        jScrollPane29 = new javax.swing.JScrollPane();
        jTextPane29 = new javax.swing.JTextPane();
        medias = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        jScrollPane9 = new javax.swing.JScrollPane();
        jTextPane9 = new javax.swing.JTextPane();
        jLabel10 = new javax.swing.JLabel();
        jScrollPane10 = new javax.swing.JScrollPane();
        jTextPane10 = new javax.swing.JTextPane();
        jLabel11 = new javax.swing.JLabel();
        jScrollPane11 = new javax.swing.JScrollPane();
        jTextPane11 = new javax.swing.JTextPane();
        jLabel12 = new javax.swing.JLabel();
        jScrollPane12 = new javax.swing.JScrollPane();
        jTextPane12 = new javax.swing.JTextPane();
        jLabel30 = new javax.swing.JLabel();
        jScrollPane30 = new javax.swing.JScrollPane();
        jTextPane30 = new javax.swing.JTextPane();
        buzos = new javax.swing.JPanel();
        jLabel13 = new javax.swing.JLabel();
        jScrollPane13 = new javax.swing.JScrollPane();
        jTextPane13 = new javax.swing.JTextPane();
        jLabel14 = new javax.swing.JLabel();
        jScrollPane14 = new javax.swing.JScrollPane();
        jTextPane14 = new javax.swing.JTextPane();
        jLabel15 = new javax.swing.JLabel();
        jScrollPane15 = new javax.swing.JScrollPane();
        jTextPane15 = new javax.swing.JTextPane();
        jLabel16 = new javax.swing.JLabel();
        jScrollPane16 = new javax.swing.JScrollPane();
        jTextPane16 = new javax.swing.JTextPane();
        jLabel35 = new javax.swing.JLabel();
        jScrollPane35 = new javax.swing.JScrollPane();
        jTextPane35 = new javax.swing.JTextPane();
        jScrollPane36 = new javax.swing.JScrollPane();
        jTextPane36 = new javax.swing.JTextPane();
        jScrollPane37 = new javax.swing.JScrollPane();
        jTextPane37 = new javax.swing.JTextPane();
        jScrollPane38 = new javax.swing.JScrollPane();
        jTextPane38 = new javax.swing.JTextPane();
        jScrollPane39 = new javax.swing.JScrollPane();
        jTextPane39 = new javax.swing.JTextPane();
        jScrollPane40 = new javax.swing.JScrollPane();
        jTextPane40 = new javax.swing.JTextPane();
        jLabel36 = new javax.swing.JLabel();
        jLabel37 = new javax.swing.JLabel();
        jLabel38 = new javax.swing.JLabel();
        jLabel39 = new javax.swing.JLabel();
        jLabel40 = new javax.swing.JLabel();
        jLabel31 = new javax.swing.JLabel();
        jScrollPane31 = new javax.swing.JScrollPane();
        jTextPane31 = new javax.swing.JTextPane();
        camisas = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextPane1 = new javax.swing.JTextPane();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTextPane2 = new javax.swing.JTextPane();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTextPane3 = new javax.swing.JTextPane();
        jLabel4 = new javax.swing.JLabel();
        jScrollPane4 = new javax.swing.JScrollPane();
        jTextPane4 = new javax.swing.JTextPane();
        jLabel17 = new javax.swing.JLabel();
        jScrollPane17 = new javax.swing.JScrollPane();
        jTextPane17 = new javax.swing.JTextPane();
        jScrollPane18 = new javax.swing.JScrollPane();
        jTextPane18 = new javax.swing.JTextPane();
        jScrollPane19 = new javax.swing.JScrollPane();
        jTextPane19 = new javax.swing.JTextPane();
        jScrollPane20 = new javax.swing.JScrollPane();
        jTextPane20 = new javax.swing.JTextPane();
        jScrollPane21 = new javax.swing.JScrollPane();
        jTextPane21 = new javax.swing.JTextPane();
        jScrollPane22 = new javax.swing.JScrollPane();
        jTextPane22 = new javax.swing.JTextPane();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jLabel32 = new javax.swing.JLabel();
        jScrollPane32 = new javax.swing.JScrollPane();
        jTextPane32 = new javax.swing.JTextPane();
        cliente = new javax.swing.JPanel();
        jLabel41 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jLabel42 = new javax.swing.JLabel();
        jTextField2 = new javax.swing.JTextField();
        jLabel43 = new javax.swing.JLabel();
        jTextField3 = new javax.swing.JTextField();
        jLabel44 = new javax.swing.JLabel();
        jTextField4 = new javax.swing.JTextField();
        jLabel45 = new javax.swing.JLabel();
        jTextField5 = new javax.swing.JTextField();
        jLabel46 = new javax.swing.JLabel();
        jTextField6 = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        pantalones.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel5.setText("Id");
        pantalones.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, -1, -1));

        jScrollPane5.setViewportView(jTextPane5);

        pantalones.add(jScrollPane5, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 10, 290, -1));

        jLabel6.setText("Identificativo");
        pantalones.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 40, -1, -1));

        jScrollPane6.setViewportView(jTextPane6);

        pantalones.add(jScrollPane6, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 40, 290, -1));

        jLabel7.setText("Nombre");
        pantalones.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 70, -1, -1));

        jScrollPane7.setViewportView(jTextPane7);

        pantalones.add(jScrollPane7, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 70, 290, -1));

        jLabel8.setText("Precio");
        pantalones.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 100, -1, -1));

        jScrollPane8.setViewportView(jTextPane8);

        pantalones.add(jScrollPane8, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 100, 290, -1));

        jLabel23.setText("XS");
        pantalones.add(jLabel23, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 130, -1, -1));

        jScrollPane23.setViewportView(jTextPane23);

        pantalones.add(jScrollPane23, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 130, 290, -1));

        jScrollPane24.setViewportView(jTextPane24);

        pantalones.add(jScrollPane24, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 160, 290, -1));

        jScrollPane25.setViewportView(jTextPane25);

        pantalones.add(jScrollPane25, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 190, 290, -1));

        jScrollPane26.setViewportView(jTextPane26);

        pantalones.add(jScrollPane26, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 220, 290, -1));

        jScrollPane27.setViewportView(jTextPane27);

        pantalones.add(jScrollPane27, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 250, 290, -1));

        jScrollPane28.setViewportView(jTextPane28);

        pantalones.add(jScrollPane28, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 280, 290, -1));

        jLabel24.setText("S");
        pantalones.add(jLabel24, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 160, -1, -1));

        jLabel25.setText("M");
        pantalones.add(jLabel25, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 190, -1, -1));

        jLabel26.setText("L");
        pantalones.add(jLabel26, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 220, -1, -1));

        jLabel27.setText("XL");
        pantalones.add(jLabel27, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 250, -1, -1));

        jLabel28.setText("XXL");
        pantalones.add(jLabel28, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 280, -1, -1));

        jLabel29.setText("Imagenes");
        pantalones.add(jLabel29, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 320, -1, -1));

        jScrollPane29.setViewportView(jTextPane29);

        pantalones.add(jScrollPane29, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 320, 290, -1));

        menu.addTab("pantalones", pantalones);

        medias.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel9.setText("Id");
        medias.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, -1, -1));

        jScrollPane9.setViewportView(jTextPane9);

        medias.add(jScrollPane9, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 10, 290, -1));

        jLabel10.setText("Identificativo");
        medias.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 40, -1, -1));

        jScrollPane10.setViewportView(jTextPane10);

        medias.add(jScrollPane10, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 40, 290, -1));

        jLabel11.setText("Nombre");
        medias.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 70, -1, -1));

        jScrollPane11.setViewportView(jTextPane11);

        medias.add(jScrollPane11, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 70, 290, -1));

        jLabel12.setText("Precio");
        medias.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 100, -1, -1));

        jScrollPane12.setViewportView(jTextPane12);

        medias.add(jScrollPane12, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 100, 290, -1));

        jLabel30.setText("Imagenes");
        medias.add(jLabel30, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 140, -1, -1));

        jScrollPane30.setViewportView(jTextPane30);

        medias.add(jScrollPane30, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 140, 290, -1));

        menu.addTab("medias", medias);

        buzos.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel13.setText("Id");
        buzos.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, -1, -1));

        jScrollPane13.setViewportView(jTextPane13);

        buzos.add(jScrollPane13, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 10, 290, -1));

        jLabel14.setText("Identificativo");
        buzos.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 40, -1, -1));

        jScrollPane14.setViewportView(jTextPane14);

        buzos.add(jScrollPane14, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 40, 290, -1));

        jLabel15.setText("Nombre");
        buzos.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 70, -1, -1));

        jScrollPane15.setViewportView(jTextPane15);

        buzos.add(jScrollPane15, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 70, 290, -1));

        jLabel16.setText("Precio");
        buzos.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 100, -1, -1));

        jScrollPane16.setViewportView(jTextPane16);

        buzos.add(jScrollPane16, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 100, 290, -1));

        jLabel35.setText("XS");
        buzos.add(jLabel35, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 130, -1, -1));

        jScrollPane35.setViewportView(jTextPane35);

        buzos.add(jScrollPane35, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 130, 290, -1));

        jScrollPane36.setViewportView(jTextPane36);

        buzos.add(jScrollPane36, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 160, 290, -1));

        jScrollPane37.setViewportView(jTextPane37);

        buzos.add(jScrollPane37, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 190, 290, -1));

        jScrollPane38.setViewportView(jTextPane38);

        buzos.add(jScrollPane38, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 220, 290, -1));

        jScrollPane39.setViewportView(jTextPane39);

        buzos.add(jScrollPane39, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 250, 290, -1));

        jScrollPane40.setViewportView(jTextPane40);

        buzos.add(jScrollPane40, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 280, 290, -1));

        jLabel36.setText("S");
        buzos.add(jLabel36, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 160, -1, -1));

        jLabel37.setText("M");
        buzos.add(jLabel37, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 190, -1, -1));

        jLabel38.setText("L");
        buzos.add(jLabel38, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 220, -1, -1));

        jLabel39.setText("XL");
        buzos.add(jLabel39, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 250, -1, -1));

        jLabel40.setText("XXL");
        buzos.add(jLabel40, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 280, -1, -1));

        jLabel31.setText("Imagenes");
        buzos.add(jLabel31, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 320, -1, -1));

        jScrollPane31.setViewportView(jTextPane31);

        buzos.add(jScrollPane31, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 320, 290, -1));

        menu.addTab("buzos", buzos);

        camisas.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setText("Id");
        camisas.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, -1, -1));

        jScrollPane1.setViewportView(jTextPane1);

        camisas.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 10, 290, -1));

        jLabel2.setText("Identificativo");
        camisas.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 40, -1, -1));

        jScrollPane2.setViewportView(jTextPane2);

        camisas.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 40, 290, -1));

        jLabel3.setText("Nombre");
        camisas.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 70, -1, -1));

        jScrollPane3.setViewportView(jTextPane3);

        camisas.add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 70, 290, -1));

        jLabel4.setText("Precio");
        camisas.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 100, -1, -1));

        jScrollPane4.setViewportView(jTextPane4);

        camisas.add(jScrollPane4, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 100, 290, -1));

        jLabel17.setText("XS");
        camisas.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 130, -1, -1));

        jScrollPane17.setViewportView(jTextPane17);

        camisas.add(jScrollPane17, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 130, 290, -1));

        jScrollPane18.setViewportView(jTextPane18);

        camisas.add(jScrollPane18, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 160, 290, -1));

        jScrollPane19.setViewportView(jTextPane19);

        camisas.add(jScrollPane19, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 190, 290, -1));

        jScrollPane20.setViewportView(jTextPane20);

        camisas.add(jScrollPane20, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 220, 290, -1));

        jScrollPane21.setViewportView(jTextPane21);

        camisas.add(jScrollPane21, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 250, 290, -1));

        jScrollPane22.setViewportView(jTextPane22);

        camisas.add(jScrollPane22, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 280, 290, -1));

        jLabel18.setText("S");
        camisas.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 160, -1, -1));

        jLabel19.setText("M");
        camisas.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 190, -1, -1));

        jLabel20.setText("L");
        camisas.add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 220, -1, -1));

        jLabel21.setText("XL");
        camisas.add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 250, -1, -1));

        jLabel22.setText("XXL");
        camisas.add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 280, -1, -1));

        jLabel32.setText("Imagenes");
        camisas.add(jLabel32, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 320, -1, -1));

        jScrollPane32.setViewportView(jTextPane32);

        camisas.add(jScrollPane32, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 320, 290, -1));

        menu.addTab("camisas", camisas);

        cliente.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel41.setText("Id");
        cliente.add(jLabel41, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, 40, -1));

        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });
        cliente.add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 10, 290, -1));

        jLabel42.setText("Correo");
        cliente.add(jLabel42, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 40, 40, -1));

        jTextField2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField2ActionPerformed(evt);
            }
        });
        cliente.add(jTextField2, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 40, 290, -1));

        jLabel43.setText("Contraseña");
        cliente.add(jLabel43, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 70, 60, -1));

        jTextField3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField3ActionPerformed(evt);
            }
        });
        cliente.add(jTextField3, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 70, 290, -1));

        jLabel44.setText("Celular");
        cliente.add(jLabel44, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 100, 40, -1));

        jTextField4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField4ActionPerformed(evt);
            }
        });
        cliente.add(jTextField4, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 100, 290, -1));

        jLabel45.setText("Compras");
        cliente.add(jLabel45, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 130, 60, -1));

        jTextField5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField5ActionPerformed(evt);
            }
        });
        cliente.add(jTextField5, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 160, 290, -1));

        jLabel46.setText("Favoritos");
        cliente.add(jLabel46, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 160, -1, -1));

        jTextField6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField6ActionPerformed(evt);
            }
        });
        cliente.add(jTextField6, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 130, 290, -1));

        menu.addTab("cliente", cliente);

        desktopPane.add(menu);
        menu.setBounds(0, 0, 400, 350);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(desktopPane, javax.swing.GroupLayout.DEFAULT_SIZE, 407, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(desktopPane, javax.swing.GroupLayout.DEFAULT_SIZE, 357, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed

    private void jTextField2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField2ActionPerformed

    private void jTextField3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField3ActionPerformed

    private void jTextField4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField4ActionPerformed

    private void jTextField6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField6ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField6ActionPerformed

    private void jTextField5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField5ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DB.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DB.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DB.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DB.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new DB().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel buzos;
    private javax.swing.JPanel camisas;
    private javax.swing.JPanel cliente;
    private javax.swing.JDesktopPane desktopPane;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel36;
    private javax.swing.JLabel jLabel37;
    private javax.swing.JLabel jLabel38;
    private javax.swing.JLabel jLabel39;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel40;
    private javax.swing.JLabel jLabel41;
    private javax.swing.JLabel jLabel42;
    private javax.swing.JLabel jLabel43;
    private javax.swing.JLabel jLabel44;
    private javax.swing.JLabel jLabel45;
    private javax.swing.JLabel jLabel46;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane10;
    private javax.swing.JScrollPane jScrollPane11;
    private javax.swing.JScrollPane jScrollPane12;
    private javax.swing.JScrollPane jScrollPane13;
    private javax.swing.JScrollPane jScrollPane14;
    private javax.swing.JScrollPane jScrollPane15;
    private javax.swing.JScrollPane jScrollPane16;
    private javax.swing.JScrollPane jScrollPane17;
    private javax.swing.JScrollPane jScrollPane18;
    private javax.swing.JScrollPane jScrollPane19;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane20;
    private javax.swing.JScrollPane jScrollPane21;
    private javax.swing.JScrollPane jScrollPane22;
    private javax.swing.JScrollPane jScrollPane23;
    private javax.swing.JScrollPane jScrollPane24;
    private javax.swing.JScrollPane jScrollPane25;
    private javax.swing.JScrollPane jScrollPane26;
    private javax.swing.JScrollPane jScrollPane27;
    private javax.swing.JScrollPane jScrollPane28;
    private javax.swing.JScrollPane jScrollPane29;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane30;
    private javax.swing.JScrollPane jScrollPane31;
    private javax.swing.JScrollPane jScrollPane32;
    private javax.swing.JScrollPane jScrollPane35;
    private javax.swing.JScrollPane jScrollPane36;
    private javax.swing.JScrollPane jScrollPane37;
    private javax.swing.JScrollPane jScrollPane38;
    private javax.swing.JScrollPane jScrollPane39;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane40;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JScrollPane jScrollPane7;
    private javax.swing.JScrollPane jScrollPane8;
    private javax.swing.JScrollPane jScrollPane9;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField5;
    private javax.swing.JTextField jTextField6;
    private javax.swing.JTextPane jTextPane1;
    private javax.swing.JTextPane jTextPane10;
    private javax.swing.JTextPane jTextPane11;
    private javax.swing.JTextPane jTextPane12;
    private javax.swing.JTextPane jTextPane13;
    private javax.swing.JTextPane jTextPane14;
    private javax.swing.JTextPane jTextPane15;
    private javax.swing.JTextPane jTextPane16;
    private javax.swing.JTextPane jTextPane17;
    private javax.swing.JTextPane jTextPane18;
    private javax.swing.JTextPane jTextPane19;
    private javax.swing.JTextPane jTextPane2;
    private javax.swing.JTextPane jTextPane20;
    private javax.swing.JTextPane jTextPane21;
    private javax.swing.JTextPane jTextPane22;
    private javax.swing.JTextPane jTextPane23;
    private javax.swing.JTextPane jTextPane24;
    private javax.swing.JTextPane jTextPane25;
    private javax.swing.JTextPane jTextPane26;
    private javax.swing.JTextPane jTextPane27;
    private javax.swing.JTextPane jTextPane28;
    private javax.swing.JTextPane jTextPane29;
    private javax.swing.JTextPane jTextPane3;
    private javax.swing.JTextPane jTextPane30;
    private javax.swing.JTextPane jTextPane31;
    private javax.swing.JTextPane jTextPane32;
    private javax.swing.JTextPane jTextPane35;
    private javax.swing.JTextPane jTextPane36;
    private javax.swing.JTextPane jTextPane37;
    private javax.swing.JTextPane jTextPane38;
    private javax.swing.JTextPane jTextPane39;
    private javax.swing.JTextPane jTextPane4;
    private javax.swing.JTextPane jTextPane40;
    private javax.swing.JTextPane jTextPane5;
    private javax.swing.JTextPane jTextPane6;
    private javax.swing.JTextPane jTextPane7;
    private javax.swing.JTextPane jTextPane8;
    private javax.swing.JTextPane jTextPane9;
    private javax.swing.JPanel medias;
    private javax.swing.JTabbedPane menu;
    private javax.swing.JPanel pantalones;
    // End of variables declaration//GEN-END:variables

}
