/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/MDIApplication.java to edit this template
 */
package FRONTEND_;

/**
 *
 * @author RSP-L16-LT-004
 */
public class Principal_Menu extends javax.swing.JFrame {

    /**
     * Creates new form Principal_Menu
     */
    public Principal_Menu() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Escritorio = new javax.swing.JDesktopPane();
        Panel_Colecciones = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        desktopPane1 = new javax.swing.JDesktopPane();
        Btn_Ropa_P1 = new javax.swing.JButton();
        Btn_Ropa_P2 = new javax.swing.JButton();
        BtnRopa_P3 = new javax.swing.JButton();
        jButton11 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        vermas = new javax.swing.JButton();
        jPanel17 = new javax.swing.JPanel();
        jButton7 = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        desktopPane2 = new javax.swing.JDesktopPane();
        jLabel11 = new javax.swing.JLabel();
        jPanel8 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jPanel7 = new javax.swing.JPanel();
        Pant = new javax.swing.JButton();
        Btn_Nove_2 = new javax.swing.JButton();
        Btn_Nove_3 = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        Btn_Nove_4 = new javax.swing.JButton();
        jLabel12 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        Btn_Nove_5 = new javax.swing.JButton();
        Btn_Nove_6 = new javax.swing.JButton();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jPanel9 = new javax.swing.JPanel();
        jLabel50 = new javax.swing.JLabel();
        jPanel14 = new javax.swing.JPanel();
        jLabel51 = new javax.swing.JLabel();
        jPanel15 = new javax.swing.JPanel();
        jLabel52 = new javax.swing.JLabel();
        jPanel16 = new javax.swing.JPanel();
        jLabel53 = new javax.swing.JLabel();
        Btn_Cat_Bu_3 = new javax.swing.JButton();
        Btn_Cat_Me_3 = new javax.swing.JButton();
        Btn_Cat_Bu_2 = new javax.swing.JButton();
        Btn_Cat_Bu_1 = new javax.swing.JButton();
        Btn_Cat_Pa_1 = new javax.swing.JButton();
        Btn_Cat_Pa_2 = new javax.swing.JButton();
        Btn_Cat_Ca_1 = new javax.swing.JButton();
        Btn_Cat_Ca_2 = new javax.swing.JButton();
        Btn_Cat_Ca_3 = new javax.swing.JButton();
        Btn_Cat_Me_1 = new javax.swing.JButton();
        Btn_Cat_Me_2 = new javax.swing.JButton();
        Btn_Cat_Pa_3 = new javax.swing.JButton();
        jLabel54 = new javax.swing.JLabel();
        jLabel55 = new javax.swing.JLabel();
        jLabel56 = new javax.swing.JLabel();
        jLabel57 = new javax.swing.JLabel();
        jLabel58 = new javax.swing.JLabel();
        jLabel59 = new javax.swing.JLabel();
        jLabel60 = new javax.swing.JLabel();
        jLabel61 = new javax.swing.JLabel();
        jLabel62 = new javax.swing.JLabel();
        jLabel63 = new javax.swing.JLabel();
        jLabel64 = new javax.swing.JLabel();
        jLabel65 = new javax.swing.JLabel();
        jLabel66 = new javax.swing.JLabel();
        jLabel67 = new javax.swing.JLabel();
        jLabel68 = new javax.swing.JLabel();
        jLabel69 = new javax.swing.JLabel();
        jLabel70 = new javax.swing.JLabel();
        jLabel71 = new javax.swing.JLabel();
        jLabel72 = new javax.swing.JLabel();
        jLabel73 = new javax.swing.JLabel();
        jLabel74 = new javax.swing.JLabel();
        jLabel75 = new javax.swing.JLabel();
        jLabel76 = new javax.swing.JLabel();
        jLabel77 = new javax.swing.JLabel();
        Btn_Cat_Bu_4 = new javax.swing.JButton();
        jLabel80 = new javax.swing.JLabel();
        jLabel81 = new javax.swing.JLabel();
        Btn_Cat_Ca_4 = new javax.swing.JButton();
        jLabel78 = new javax.swing.JLabel();
        jLabel79 = new javax.swing.JLabel();
        Btn_Cat_Me_4 = new javax.swing.JButton();
        jLabel82 = new javax.swing.JLabel();
        jLabel83 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        Btn_Col_HA_3 = new javax.swing.JButton();
        jPanel10 = new javax.swing.JPanel();
        jLabel23 = new javax.swing.JLabel();
        Btn_Col_Ghi_3 = new javax.swing.JButton();
        Btn_Col_HA_2 = new javax.swing.JButton();
        jPanel11 = new javax.swing.JPanel();
        jLabel21 = new javax.swing.JLabel();
        jPanel12 = new javax.swing.JPanel();
        jLabel24 = new javax.swing.JLabel();
        jPanel13 = new javax.swing.JPanel();
        jLabel22 = new javax.swing.JLabel();
        Btn_Col_HA_1 = new javax.swing.JButton();
        Btn_Col_Uzu_1 = new javax.swing.JButton();
        Btn_Col_Uzu_2 = new javax.swing.JButton();
        Btn_Col_Uzu_4 = new javax.swing.JButton();
        Btn_Col_Kuro_1 = new javax.swing.JButton();
        Btn_Col_Kuro_2 = new javax.swing.JButton();
        Btn_Col_Kuro_3 = new javax.swing.JButton();
        Btn_Col_Ghi_1 = new javax.swing.JButton();
        Btn_Col_Ghi_2 = new javax.swing.JButton();
        Btn_Col_Uzu_3 = new javax.swing.JButton();
        jLabel35 = new javax.swing.JLabel();
        jLabel43 = new javax.swing.JLabel();
        jLabel84 = new javax.swing.JLabel();
        jLabel85 = new javax.swing.JLabel();
        jLabel86 = new javax.swing.JLabel();
        jLabel87 = new javax.swing.JLabel();
        jLabel88 = new javax.swing.JLabel();
        jLabel89 = new javax.swing.JLabel();
        jLabel90 = new javax.swing.JLabel();
        jLabel91 = new javax.swing.JLabel();
        jLabel92 = new javax.swing.JLabel();
        jLabel93 = new javax.swing.JLabel();
        jLabel94 = new javax.swing.JLabel();
        jLabel95 = new javax.swing.JLabel();
        jLabel96 = new javax.swing.JLabel();
        jLabel97 = new javax.swing.JLabel();
        jLabel98 = new javax.swing.JLabel();
        jLabel99 = new javax.swing.JLabel();
        jLabel100 = new javax.swing.JLabel();
        jLabel101 = new javax.swing.JLabel();
        jLabel102 = new javax.swing.JLabel();
        jLabel103 = new javax.swing.JLabel();
        jLabel104 = new javax.swing.JLabel();
        jLabel105 = new javax.swing.JLabel();
        jLabel106 = new javax.swing.JLabel();
        jLabel107 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        Btn_Carrito = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        textField1 = new java.awt.TextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 208, 208));

        Escritorio.setBackground(new java.awt.Color(255, 208, 208));
        Escritorio.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Panel_Colecciones.setBackground(new java.awt.Color(255, 208, 208));
        Panel_Colecciones.setTabPlacement(javax.swing.JTabbedPane.LEFT);
        Panel_Colecciones.setFont(new java.awt.Font("Swis721 Hv BT", 3, 14)); // NOI18N

        desktopPane1.setBackground(new java.awt.Color(255, 204, 153));
        desktopPane1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Btn_Ropa_P1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes_Ropa/Pa_3.jpeg"))); // NOI18N
        Btn_Ropa_P1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Btn_Ropa_P1MouseClicked(evt);
            }
        });
        Btn_Ropa_P1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Btn_Ropa_P1ActionPerformed(evt);
            }
        });
        desktopPane1.setLayer(Btn_Ropa_P1, javax.swing.JLayeredPane.POPUP_LAYER);
        desktopPane1.add(Btn_Ropa_P1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 380, 160, 200));

        Btn_Ropa_P2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes_Ropa/Bu_1.jpeg"))); // NOI18N
        Btn_Ropa_P2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Btn_Ropa_P2MouseClicked(evt);
            }
        });
        Btn_Ropa_P2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Btn_Ropa_P2ActionPerformed(evt);
            }
        });
        desktopPane1.setLayer(Btn_Ropa_P2, javax.swing.JLayeredPane.POPUP_LAYER);
        desktopPane1.add(Btn_Ropa_P2, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 380, 160, 200));

        BtnRopa_P3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes_Ropa/Ca_1.jpeg"))); // NOI18N
        BtnRopa_P3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BtnRopa_P3MouseClicked(evt);
            }
        });
        desktopPane1.setLayer(BtnRopa_P3, javax.swing.JLayeredPane.POPUP_LAYER);
        desktopPane1.add(BtnRopa_P3, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 380, 160, 200));

        jButton11.setBackground(new java.awt.Color(255, 208, 208));
        jButton11.setFont(new java.awt.Font("Swis721 Hv BT", 3, 12)); // NOI18N
        jButton11.setText("      EXPLORA   >");
        jButton11.setBorder(null);
        jButton11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton11ActionPerformed(evt);
            }
        });
        desktopPane1.setLayer(jButton11, javax.swing.JLayeredPane.POPUP_LAYER);
        desktopPane1.add(jButton11, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 380, 160, 200));

        jLabel2.setFont(new java.awt.Font("Showcard Gothic", 0, 36)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("PETITE BOUTIQUE");
        desktopPane1.setLayer(jLabel2, javax.swing.JLayeredPane.POPUP_LAYER);
        desktopPane1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 160, 340, 50));

        jLabel5.setFont(new java.awt.Font("Swis721 Hv BT", 3, 12)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("CREA TU PROPIO ESTILO");
        desktopPane1.setLayer(jLabel5, javax.swing.JLayeredPane.POPUP_LAYER);
        desktopPane1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 210, 220, -1));

        vermas.setFont(new java.awt.Font("Swis721 Hv BT", 3, 12)); // NOI18N
        vermas.setText("Ver más");
        vermas.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                vermasMouseClicked(evt);
            }
        });
        vermas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                vermasActionPerformed(evt);
            }
        });
        desktopPane1.setLayer(vermas, javax.swing.JLayeredPane.POPUP_LAYER);
        desktopPane1.add(vermas, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 250, 110, 30));

        jPanel17.setBackground(new java.awt.Color(255, 204, 153));
        jPanel17.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/FRONTEND_IMAGENESS/koaj-CT-202340239 (1).jpg"))); // NOI18N
        jPanel17.add(jButton7, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -10, 750, 430));

        desktopPane1.add(jPanel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 730, 650));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(desktopPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 731, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(desktopPane1)
        );

        Panel_Colecciones.addTab("Principal", jPanel1);

        desktopPane2.setBackground(new java.awt.Color(255, 204, 153));
        desktopPane2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel11.setFont(new java.awt.Font("Swis721 Hv BT", 2, 12)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        desktopPane2.setLayer(jLabel11, javax.swing.JLayeredPane.POPUP_LAYER);
        desktopPane2.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 600, 220, -1));

        jPanel8.setBackground(new java.awt.Color(255, 204, 153));
        jPanel8.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel6.setFont(new java.awt.Font("Showcard Gothic", 0, 36)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Productos");
        jPanel8.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 30, 220, -1));

        jPanel7.setBackground(new java.awt.Color(255, 102, 102));

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 710, Short.MAX_VALUE)
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 50, Short.MAX_VALUE)
        );

        jPanel8.add(jPanel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 20, 710, 50));

        Pant.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes_Ropa/Pa_3.jpeg"))); // NOI18N
        Pant.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                PantMouseClicked(evt);
            }
        });
        Pant.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PantActionPerformed(evt);
            }
        });
        jPanel8.add(Pant, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 110, 160, 200));

        Btn_Nove_2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes_Ropa/Bu_1.jpeg"))); // NOI18N
        Btn_Nove_2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Btn_Nove_2MouseClicked(evt);
            }
        });
        Btn_Nove_2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Btn_Nove_2ActionPerformed(evt);
            }
        });
        jPanel8.add(Btn_Nove_2, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 110, 160, 200));

        Btn_Nove_3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes_Ropa/Ca_1.jpeg"))); // NOI18N
        Btn_Nove_3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Btn_Nove_3MouseClicked(evt);
            }
        });
        jPanel8.add(Btn_Nove_3, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 110, 160, 200));

        jLabel7.setFont(new java.awt.Font("Swis721 Hv BT", 2, 12)); // NOI18N
        jLabel7.setText("Camiseta overside ");
        jPanel8.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 320, 110, -1));

        jLabel9.setFont(new java.awt.Font("Swis721 Hv BT", 2, 12)); // NOI18N
        jLabel9.setText("$35.000");
        jPanel8.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 340, 60, -1));

        jLabel8.setFont(new java.awt.Font("Swis721 Hv BT", 2, 12)); // NOI18N
        jLabel8.setText("Buzo overside unisex");
        jPanel8.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 320, 120, -1));

        jLabel15.setFont(new java.awt.Font("Swis721 Hv BT", 2, 12)); // NOI18N
        jLabel15.setText("$69.000");
        jPanel8.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 340, 70, -1));

        jLabel13.setFont(new java.awt.Font("Swis721 Hv BT", 2, 12)); // NOI18N
        jLabel13.setText("Pantalón cargo ");
        jPanel8.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 320, 90, -1));

        jLabel16.setFont(new java.awt.Font("Swis721 Hv BT", 2, 12)); // NOI18N
        jLabel16.setText("$50.000");
        jPanel8.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 340, 70, -1));

        Btn_Nove_4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes_Ropa/Su_1.png"))); // NOI18N
        Btn_Nove_4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Btn_Nove_4MouseClicked(evt);
            }
        });
        Btn_Nove_4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Btn_Nove_4ActionPerformed(evt);
            }
        });
        jPanel8.add(Btn_Nove_4, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 370, 160, 200));

        jLabel12.setFont(new java.awt.Font("Swis721 Hv BT", 2, 12)); // NOI18N
        jLabel12.setText("Sueter lana unisex");
        jPanel8.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 580, 130, -1));

        jLabel17.setFont(new java.awt.Font("Swis721 Hv BT", 2, 12)); // NOI18N
        jLabel17.setText("$69.000");
        jPanel8.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 600, 90, -1));

        jLabel10.setFont(new java.awt.Font("Swis721 Hv BT", 2, 12)); // NOI18N
        jLabel10.setText("Pack de medias Kuromi");
        jPanel8.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 580, 130, -1));

        jLabel14.setFont(new java.awt.Font("Swis721 Hv BT", 2, 12)); // NOI18N
        jLabel14.setText("$10.000");
        jPanel8.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 600, 90, -1));

        Btn_Nove_5.setBackground(new java.awt.Color(255, 208, 208));
        Btn_Nove_5.setFont(new java.awt.Font("Swis721 Hv BT", 0, 12)); // NOI18N
        Btn_Nove_5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes_Ropa/Me_Kuromi_2.jpg"))); // NOI18N
        Btn_Nove_5.setBorder(null);
        Btn_Nove_5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Btn_Nove_5MouseClicked(evt);
            }
        });
        Btn_Nove_5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Btn_Nove_5ActionPerformed(evt);
            }
        });
        jPanel8.add(Btn_Nove_5, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 370, -1, -1));

        Btn_Nove_6.setBackground(new java.awt.Color(255, 208, 208));
        Btn_Nove_6.setFont(new java.awt.Font("Swis721 Hv BT", 0, 12)); // NOI18N
        Btn_Nove_6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes_Ropa/Bu_Ghibli.jpg"))); // NOI18N
        Btn_Nove_6.setBorder(null);
        Btn_Nove_6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Btn_Nove_6MouseClicked(evt);
            }
        });
        Btn_Nove_6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Btn_Nove_6ActionPerformed(evt);
            }
        });
        jPanel8.add(Btn_Nove_6, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 370, -1, -1));

        jLabel18.setFont(new java.awt.Font("Swis721 Hv BT", 2, 12)); // NOI18N
        jLabel18.setText("Buzo Ghibli");
        jPanel8.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 580, 120, -1));

        jLabel19.setFont(new java.awt.Font("Swis721 Hv BT", 2, 12)); // NOI18N
        jLabel19.setText("$69.000");
        jPanel8.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 600, 80, -1));

        desktopPane2.add(jPanel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 730, 650));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(desktopPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 731, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(desktopPane2)
        );

        Panel_Colecciones.addTab("Novedades", jPanel2);

        jPanel3.setBackground(new java.awt.Color(255, 204, 153));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel9.setBackground(new java.awt.Color(255, 102, 102));
        jPanel9.setForeground(new java.awt.Color(255, 102, 102));

        jLabel50.setBackground(new java.awt.Color(102, 0, 0));
        jLabel50.setFont(new java.awt.Font("Snap ITC", 0, 12)); // NOI18N
        jLabel50.setText("Medias");

        javax.swing.GroupLayout jPanel9Layout = new javax.swing.GroupLayout(jPanel9);
        jPanel9.setLayout(jPanel9Layout);
        jPanel9Layout.setHorizontalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addComponent(jLabel50)
                .addContainerGap(43, Short.MAX_VALUE))
        );
        jPanel9Layout.setVerticalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel50, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jPanel3.add(jPanel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 10, 120, 30));

        jPanel14.setBackground(new java.awt.Color(255, 102, 102));
        jPanel14.setForeground(new java.awt.Color(255, 102, 102));

        jLabel51.setBackground(new java.awt.Color(102, 0, 0));
        jLabel51.setFont(new java.awt.Font("Snap ITC", 0, 12)); // NOI18N
        jLabel51.setText("Buzos");

        javax.swing.GroupLayout jPanel14Layout = new javax.swing.GroupLayout(jPanel14);
        jPanel14.setLayout(jPanel14Layout);
        jPanel14Layout.setHorizontalGroup(
            jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel14Layout.createSequentialGroup()
                .addContainerGap(44, Short.MAX_VALUE)
                .addComponent(jLabel51)
                .addGap(42, 42, 42))
        );
        jPanel14Layout.setVerticalGroup(
            jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel51, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jPanel3.add(jPanel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, 120, 30));

        jPanel15.setBackground(new java.awt.Color(255, 102, 102));
        jPanel15.setForeground(new java.awt.Color(255, 102, 102));

        jLabel52.setBackground(new java.awt.Color(102, 0, 0));
        jLabel52.setFont(new java.awt.Font("Snap ITC", 0, 12)); // NOI18N
        jLabel52.setText("Pantalones");

        javax.swing.GroupLayout jPanel15Layout = new javax.swing.GroupLayout(jPanel15);
        jPanel15.setLayout(jPanel15Layout);
        jPanel15Layout.setHorizontalGroup(
            jPanel15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel15Layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addComponent(jLabel52)
                .addContainerGap(31, Short.MAX_VALUE))
        );
        jPanel15Layout.setVerticalGroup(
            jPanel15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel52, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jPanel3.add(jPanel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 10, 120, 30));

        jPanel16.setBackground(new java.awt.Color(255, 102, 102));
        jPanel16.setForeground(new java.awt.Color(255, 102, 102));

        jLabel53.setBackground(new java.awt.Color(102, 0, 0));
        jLabel53.setFont(new java.awt.Font("Snap ITC", 0, 12)); // NOI18N
        jLabel53.setText("Camisetas");

        javax.swing.GroupLayout jPanel16Layout = new javax.swing.GroupLayout(jPanel16);
        jPanel16.setLayout(jPanel16Layout);
        jPanel16Layout.setHorizontalGroup(
            jPanel16Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel16Layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addComponent(jLabel53)
                .addContainerGap(31, Short.MAX_VALUE))
        );
        jPanel16Layout.setVerticalGroup(
            jPanel16Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel53, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jPanel3.add(jPanel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 10, 120, 30));

        Btn_Cat_Bu_3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes_Ropa_Pequeño/Bu_Hora_P.jpg"))); // NOI18N
        Btn_Cat_Bu_3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Btn_Cat_Bu_3MouseClicked(evt);
            }
        });
        Btn_Cat_Bu_3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Btn_Cat_Bu_3ActionPerformed(evt);
            }
        });
        jPanel3.add(Btn_Cat_Bu_3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 350, 100, 110));

        Btn_Cat_Me_3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes_Ropa_Pequeño/Me_Kuromi_P2.jpg"))); // NOI18N
        Btn_Cat_Me_3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Btn_Cat_Me_3MouseClicked(evt);
            }
        });
        Btn_Cat_Me_3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Btn_Cat_Me_3ActionPerformed(evt);
            }
        });
        jPanel3.add(Btn_Cat_Me_3, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 350, 100, 110));

        Btn_Cat_Bu_2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes_Ropa_Pequeño/Bu_Kuromi_P.jpg"))); // NOI18N
        Btn_Cat_Bu_2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Btn_Cat_Bu_2MouseClicked(evt);
            }
        });
        Btn_Cat_Bu_2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Btn_Cat_Bu_2ActionPerformed(evt);
            }
        });
        jPanel3.add(Btn_Cat_Bu_2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 200, 100, 110));

        Btn_Cat_Bu_1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes_Ropa_Pequeño/Bu_Ghibli_P.jpg"))); // NOI18N
        Btn_Cat_Bu_1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Btn_Cat_Bu_1MouseClicked(evt);
            }
        });
        Btn_Cat_Bu_1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Btn_Cat_Bu_1ActionPerformed(evt);
            }
        });
        jPanel3.add(Btn_Cat_Bu_1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 50, 100, 110));

        Btn_Cat_Pa_1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes_Ropa_Pequeño/Pa_1.jpg"))); // NOI18N
        Btn_Cat_Pa_1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Btn_Cat_Pa_1MouseClicked(evt);
            }
        });
        Btn_Cat_Pa_1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Btn_Cat_Pa_1ActionPerformed(evt);
            }
        });
        jPanel3.add(Btn_Cat_Pa_1, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 50, 100, 110));

        Btn_Cat_Pa_2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes_Ropa_Pequeño/Pa_2.jpg"))); // NOI18N
        Btn_Cat_Pa_2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Btn_Cat_Pa_2MouseClicked(evt);
            }
        });
        Btn_Cat_Pa_2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Btn_Cat_Pa_2ActionPerformed(evt);
            }
        });
        jPanel3.add(Btn_Cat_Pa_2, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 200, 100, 110));

        Btn_Cat_Ca_1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes_Ropa_Pequeño/Ca_Ghibli_P.jpg"))); // NOI18N
        Btn_Cat_Ca_1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Btn_Cat_Ca_1MouseClicked(evt);
            }
        });
        Btn_Cat_Ca_1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Btn_Cat_Ca_1ActionPerformed(evt);
            }
        });
        jPanel3.add(Btn_Cat_Ca_1, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 50, 100, 110));

        Btn_Cat_Ca_2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes_Ropa_Pequeño/Ca_Hora_P.jpg"))); // NOI18N
        Btn_Cat_Ca_2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Btn_Cat_Ca_2MouseClicked(evt);
            }
        });
        Btn_Cat_Ca_2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Btn_Cat_Ca_2ActionPerformed(evt);
            }
        });
        jPanel3.add(Btn_Cat_Ca_2, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 200, 100, 110));

        Btn_Cat_Ca_3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes_Ropa_Pequeño/Ca_Uzumaki_P.jpg"))); // NOI18N
        Btn_Cat_Ca_3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Btn_Cat_Ca_3MouseClicked(evt);
            }
        });
        Btn_Cat_Ca_3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Btn_Cat_Ca_3ActionPerformed(evt);
            }
        });
        jPanel3.add(Btn_Cat_Ca_3, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 350, 100, 110));

        Btn_Cat_Me_1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes_Ropa_Pequeño/Me_Hora_P.jpg"))); // NOI18N
        Btn_Cat_Me_1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Btn_Cat_Me_1MouseClicked(evt);
            }
        });
        Btn_Cat_Me_1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Btn_Cat_Me_1ActionPerformed(evt);
            }
        });
        jPanel3.add(Btn_Cat_Me_1, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 50, 100, 110));

        Btn_Cat_Me_2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes_Ropa_Pequeño/Me_Ghibli_P.jpg"))); // NOI18N
        Btn_Cat_Me_2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Btn_Cat_Me_2MouseClicked(evt);
            }
        });
        Btn_Cat_Me_2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Btn_Cat_Me_2ActionPerformed(evt);
            }
        });
        jPanel3.add(Btn_Cat_Me_2, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 200, 100, 110));

        Btn_Cat_Pa_3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes_Ropa_Pequeño/Pa_3.jpeg"))); // NOI18N
        Btn_Cat_Pa_3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Btn_Cat_Pa_3MouseClicked(evt);
            }
        });
        Btn_Cat_Pa_3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Btn_Cat_Pa_3ActionPerformed(evt);
            }
        });
        jPanel3.add(Btn_Cat_Pa_3, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 350, 100, 110));

        jLabel54.setFont(new java.awt.Font("Swis721 Hv BT", 2, 12)); // NOI18N
        jLabel54.setText("Buzo Ghibli");
        jPanel3.add(jLabel54, new org.netbeans.lib.awtextra.AbsoluteConstraints(42, 160, 80, -1));

        jLabel55.setFont(new java.awt.Font("Swis721 Hv BT", 2, 12)); // NOI18N
        jLabel55.setText("$80.000");
        jPanel3.add(jLabel55, new org.netbeans.lib.awtextra.AbsoluteConstraints(56, 180, 50, -1));

        jLabel56.setFont(new java.awt.Font("Swis721 Hv BT", 2, 12)); // NOI18N
        jLabel56.setText("Pantalon cargo 1");
        jPanel3.add(jLabel56, new org.netbeans.lib.awtextra.AbsoluteConstraints(217, 160, 100, -1));

        jLabel57.setFont(new java.awt.Font("Swis721 Hv BT", 2, 12)); // NOI18N
        jLabel57.setText("$50.000");
        jPanel3.add(jLabel57, new org.netbeans.lib.awtextra.AbsoluteConstraints(236, 180, 50, -1));

        jLabel58.setFont(new java.awt.Font("Swis721 Hv BT", 2, 12)); // NOI18N
        jLabel58.setText("Buzo Ghibli");
        jPanel3.add(jLabel58, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 160, 90, -1));

        jLabel59.setFont(new java.awt.Font("Swis721 Hv BT", 2, 12)); // NOI18N
        jLabel59.setText("$80.000");
        jPanel3.add(jLabel59, new org.netbeans.lib.awtextra.AbsoluteConstraints(416, 180, 50, -1));

        jLabel60.setFont(new java.awt.Font("Swis721 Hv BT", 2, 12)); // NOI18N
        jLabel60.setText("Medias Hora de Aventura");
        jPanel3.add(jLabel60, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 160, 160, -1));

        jLabel61.setFont(new java.awt.Font("Swis721 Hv BT", 2, 12)); // NOI18N
        jLabel61.setText("$10.000");
        jPanel3.add(jLabel61, new org.netbeans.lib.awtextra.AbsoluteConstraints(596, 180, 50, -1));

        jLabel62.setFont(new java.awt.Font("Swis721 Hv BT", 2, 12)); // NOI18N
        jLabel62.setText("Buzo Kuromi");
        jPanel3.add(jLabel62, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 310, -1, -1));

        jLabel63.setFont(new java.awt.Font("Swis721 Hv BT", 2, 12)); // NOI18N
        jLabel63.setText("$80.000");
        jPanel3.add(jLabel63, new org.netbeans.lib.awtextra.AbsoluteConstraints(56, 330, 50, -1));

        jLabel64.setFont(new java.awt.Font("Swis721 Hv BT", 2, 12)); // NOI18N
        jLabel64.setText("Pantalon cargo 2");
        jPanel3.add(jLabel64, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 310, 100, -1));

        jLabel65.setFont(new java.awt.Font("Swis721 Hv BT", 2, 12)); // NOI18N
        jLabel65.setText("$50.000");
        jPanel3.add(jLabel65, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 330, -1, -1));

        jLabel66.setFont(new java.awt.Font("Swis721 Hv BT", 2, 12)); // NOI18N
        jLabel66.setText("Camisa Hora de Aventura");
        jPanel3.add(jLabel66, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 310, 170, -1));

        jLabel67.setFont(new java.awt.Font("Swis721 Hv BT", 2, 12)); // NOI18N
        jLabel67.setText("$45.000");
        jPanel3.add(jLabel67, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 330, 90, -1));

        jLabel68.setFont(new java.awt.Font("Swis721 Hv BT", 2, 12)); // NOI18N
        jLabel68.setText("Medias Ghibli");
        jPanel3.add(jLabel68, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 310, 100, -1));

        jLabel69.setFont(new java.awt.Font("Swis721 Hv BT", 2, 12)); // NOI18N
        jLabel69.setText("$10.000");
        jPanel3.add(jLabel69, new org.netbeans.lib.awtextra.AbsoluteConstraints(596, 330, 50, -1));

        jLabel70.setFont(new java.awt.Font("Swis721 Hv BT", 2, 12)); // NOI18N
        jLabel70.setText("Buzo Hora de Aventura ");
        jPanel3.add(jLabel70, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 460, 150, -1));

        jLabel71.setFont(new java.awt.Font("Swis721 Hv BT", 2, 12)); // NOI18N
        jLabel71.setText("$80.000");
        jPanel3.add(jLabel71, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 480, 50, -1));

        jLabel72.setFont(new java.awt.Font("Swis721 Hv BT", 2, 12)); // NOI18N
        jLabel72.setText("Pantalon cargo 3");
        jPanel3.add(jLabel72, new org.netbeans.lib.awtextra.AbsoluteConstraints(217, 460, 100, -1));

        jLabel73.setFont(new java.awt.Font("Swis721 Hv BT", 2, 12)); // NOI18N
        jLabel73.setText("$50.000");
        jPanel3.add(jLabel73, new org.netbeans.lib.awtextra.AbsoluteConstraints(236, 480, 50, -1));

        jLabel74.setFont(new java.awt.Font("Swis721 Hv BT", 2, 12)); // NOI18N
        jLabel74.setText("Camiseta Uzumaki Model 1");
        jPanel3.add(jLabel74, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 460, 170, -1));

        jLabel75.setFont(new java.awt.Font("Swis721 Hv BT", 2, 12)); // NOI18N
        jLabel75.setText("$45.000");
        jPanel3.add(jLabel75, new org.netbeans.lib.awtextra.AbsoluteConstraints(416, 480, 50, -1));

        jLabel76.setFont(new java.awt.Font("Swis721 Hv BT", 2, 12)); // NOI18N
        jLabel76.setText("Medias Kuromi");
        jPanel3.add(jLabel76, new org.netbeans.lib.awtextra.AbsoluteConstraints(567, 460, 100, -1));

        jLabel77.setFont(new java.awt.Font("Swis721 Hv BT", 2, 12)); // NOI18N
        jLabel77.setText("$10.000");
        jPanel3.add(jLabel77, new org.netbeans.lib.awtextra.AbsoluteConstraints(596, 480, 50, -1));

        Btn_Cat_Bu_4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes_Ropa_Pequeño/Bu_Uzumaki_P.jpg"))); // NOI18N
        Btn_Cat_Bu_4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Btn_Cat_Bu_4MouseClicked(evt);
            }
        });
        Btn_Cat_Bu_4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Btn_Cat_Bu_4ActionPerformed(evt);
            }
        });
        jPanel3.add(Btn_Cat_Bu_4, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 500, 100, 110));

        jLabel80.setFont(new java.awt.Font("Swis721 Hv BT", 2, 12)); // NOI18N
        jLabel80.setText("Buzo Uzumaki");
        jPanel3.add(jLabel80, new org.netbeans.lib.awtextra.AbsoluteConstraints(37, 610, 90, -1));

        jLabel81.setFont(new java.awt.Font("Swis721 Hv BT", 2, 12)); // NOI18N
        jLabel81.setText("$80.000");
        jPanel3.add(jLabel81, new org.netbeans.lib.awtextra.AbsoluteConstraints(56, 630, 50, -1));

        Btn_Cat_Ca_4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes_Ropa_Pequeño/Ca_Uzumaki_P2.jpg"))); // NOI18N
        Btn_Cat_Ca_4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Btn_Cat_Ca_4MouseClicked(evt);
            }
        });
        Btn_Cat_Ca_4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Btn_Cat_Ca_4ActionPerformed(evt);
            }
        });
        jPanel3.add(Btn_Cat_Ca_4, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 500, 100, 110));

        jLabel78.setFont(new java.awt.Font("Swis721 Hv BT", 2, 12)); // NOI18N
        jLabel78.setText("Camiseta Uzumaki Model 2");
        jPanel3.add(jLabel78, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 610, 170, -1));

        jLabel79.setFont(new java.awt.Font("Swis721 Hv BT", 2, 12)); // NOI18N
        jLabel79.setText("$45.000");
        jPanel3.add(jLabel79, new org.netbeans.lib.awtextra.AbsoluteConstraints(416, 630, 50, -1));

        Btn_Cat_Me_4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes_Ropa_Pequeño/Me_Uzumaki_P.jpg"))); // NOI18N
        Btn_Cat_Me_4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Btn_Cat_Me_4MouseClicked(evt);
            }
        });
        Btn_Cat_Me_4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Btn_Cat_Me_4ActionPerformed(evt);
            }
        });
        jPanel3.add(Btn_Cat_Me_4, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 500, 100, 110));

        jLabel82.setFont(new java.awt.Font("Swis721 Hv BT", 2, 12)); // NOI18N
        jLabel82.setText("Medias Uzumaki");
        jPanel3.add(jLabel82, new org.netbeans.lib.awtextra.AbsoluteConstraints(567, 610, 100, -1));

        jLabel83.setFont(new java.awt.Font("Swis721 Hv BT", 2, 12)); // NOI18N
        jLabel83.setText("$10.000");
        jPanel3.add(jLabel83, new org.netbeans.lib.awtextra.AbsoluteConstraints(596, 630, 50, -1));

        Panel_Colecciones.addTab("Categorias", jPanel3);

        jPanel4.setBackground(new java.awt.Color(255, 204, 153));
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Btn_Col_HA_3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes_Ropa_Pequeño/Ca_Hora_P.jpg"))); // NOI18N
        Btn_Col_HA_3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Btn_Col_HA_3MouseClicked(evt);
            }
        });
        Btn_Col_HA_3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Btn_Col_HA_3ActionPerformed(evt);
            }
        });
        jPanel4.add(Btn_Col_HA_3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 350, 100, 110));

        jPanel10.setBackground(new java.awt.Color(255, 102, 102));

        jLabel23.setBackground(new java.awt.Color(102, 0, 0));
        jLabel23.setFont(new java.awt.Font("Snap ITC", 0, 12)); // NOI18N
        jLabel23.setText("Ghibli");

        javax.swing.GroupLayout jPanel10Layout = new javax.swing.GroupLayout(jPanel10);
        jPanel10.setLayout(jPanel10Layout);
        jPanel10Layout.setHorizontalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel10Layout.createSequentialGroup()
                .addGap(46, 46, 46)
                .addComponent(jLabel23)
                .addContainerGap(45, Short.MAX_VALUE))
        );
        jPanel10Layout.setVerticalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel23, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jPanel4.add(jPanel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 10, 120, 30));

        Btn_Col_Ghi_3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes_Ropa_Pequeño/Me_Ghibli_P.jpg"))); // NOI18N
        Btn_Col_Ghi_3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Btn_Col_Ghi_3MouseClicked(evt);
            }
        });
        Btn_Col_Ghi_3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Btn_Col_Ghi_3ActionPerformed(evt);
            }
        });
        jPanel4.add(Btn_Col_Ghi_3, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 350, 100, 110));

        Btn_Col_HA_2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes_Ropa_Pequeño/Bu_Hora_P.jpg"))); // NOI18N
        Btn_Col_HA_2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Btn_Col_HA_2MouseClicked(evt);
            }
        });
        Btn_Col_HA_2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Btn_Col_HA_2ActionPerformed(evt);
            }
        });
        jPanel4.add(Btn_Col_HA_2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 200, 100, 110));

        jPanel11.setBackground(new java.awt.Color(255, 102, 102));

        jLabel21.setBackground(new java.awt.Color(102, 0, 0));
        jLabel21.setFont(new java.awt.Font("Snap ITC", 0, 12)); // NOI18N
        jLabel21.setText("Hora de aventura");

        javax.swing.GroupLayout jPanel11Layout = new javax.swing.GroupLayout(jPanel11);
        jPanel11.setLayout(jPanel11Layout);
        jPanel11Layout.setHorizontalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel11Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jLabel21, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel11Layout.setVerticalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel21, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jPanel4.add(jPanel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, 120, 30));

        jPanel12.setBackground(new java.awt.Color(255, 102, 102));

        jLabel24.setBackground(new java.awt.Color(102, 0, 0));
        jLabel24.setFont(new java.awt.Font("Snap ITC", 0, 12)); // NOI18N
        jLabel24.setText("Uzumaki");

        javax.swing.GroupLayout jPanel12Layout = new javax.swing.GroupLayout(jPanel12);
        jPanel12.setLayout(jPanel12Layout);
        jPanel12Layout.setHorizontalGroup(
            jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel12Layout.createSequentialGroup()
                .addContainerGap(36, Short.MAX_VALUE)
                .addComponent(jLabel24)
                .addGap(38, 38, 38))
        );
        jPanel12Layout.setVerticalGroup(
            jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel24, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jPanel4.add(jPanel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 10, 120, 30));

        jPanel13.setBackground(new java.awt.Color(255, 102, 102));

        jLabel22.setBackground(new java.awt.Color(102, 0, 0));
        jLabel22.setFont(new java.awt.Font("Snap ITC", 0, 12)); // NOI18N
        jLabel22.setText("Kuromi");

        javax.swing.GroupLayout jPanel13Layout = new javax.swing.GroupLayout(jPanel13);
        jPanel13.setLayout(jPanel13Layout);
        jPanel13Layout.setHorizontalGroup(
            jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel13Layout.createSequentialGroup()
                .addGap(46, 46, 46)
                .addComponent(jLabel22)
                .addContainerGap(36, Short.MAX_VALUE))
        );
        jPanel13Layout.setVerticalGroup(
            jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel22, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jPanel4.add(jPanel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 10, 120, 30));

        Btn_Col_HA_1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes_Ropa_Pequeño/Me_Hora_P2.jpg"))); // NOI18N
        Btn_Col_HA_1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Btn_Col_HA_1MouseClicked(evt);
            }
        });
        Btn_Col_HA_1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Btn_Col_HA_1ActionPerformed(evt);
            }
        });
        jPanel4.add(Btn_Col_HA_1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 50, 100, 110));

        Btn_Col_Uzu_1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes_Ropa_Pequeño/Me_Uzumaki_P.jpg"))); // NOI18N
        Btn_Col_Uzu_1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Btn_Col_Uzu_1MouseClicked(evt);
            }
        });
        Btn_Col_Uzu_1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Btn_Col_Uzu_1ActionPerformed(evt);
            }
        });
        jPanel4.add(Btn_Col_Uzu_1, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 50, 100, 110));

        Btn_Col_Uzu_2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes_Ropa_Pequeño/Ca_Uzumaki_P.jpg"))); // NOI18N
        Btn_Col_Uzu_2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Btn_Col_Uzu_2MouseClicked(evt);
            }
        });
        Btn_Col_Uzu_2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Btn_Col_Uzu_2ActionPerformed(evt);
            }
        });
        jPanel4.add(Btn_Col_Uzu_2, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 200, 100, 110));

        Btn_Col_Uzu_4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes_Ropa_Pequeño/Bu_Uzumaki_P.jpg"))); // NOI18N
        Btn_Col_Uzu_4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Btn_Col_Uzu_4MouseClicked(evt);
            }
        });
        Btn_Col_Uzu_4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Btn_Col_Uzu_4ActionPerformed(evt);
            }
        });
        jPanel4.add(Btn_Col_Uzu_4, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 500, 100, 110));

        Btn_Col_Kuro_1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes_Ropa_Pequeño/Bu_Kuromi_P.jpg"))); // NOI18N
        Btn_Col_Kuro_1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Btn_Col_Kuro_1MouseClicked(evt);
            }
        });
        Btn_Col_Kuro_1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Btn_Col_Kuro_1ActionPerformed(evt);
            }
        });
        jPanel4.add(Btn_Col_Kuro_1, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 50, 100, 110));

        Btn_Col_Kuro_2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes_Ropa_Pequeño/Ca_Kuromi_P.jpg"))); // NOI18N
        Btn_Col_Kuro_2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Btn_Col_Kuro_2MouseClicked(evt);
            }
        });
        Btn_Col_Kuro_2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Btn_Col_Kuro_2ActionPerformed(evt);
            }
        });
        jPanel4.add(Btn_Col_Kuro_2, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 200, 100, 110));

        Btn_Col_Kuro_3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes_Ropa_Pequeño/Me_Kuromi_P2.jpg"))); // NOI18N
        Btn_Col_Kuro_3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Btn_Col_Kuro_3MouseClicked(evt);
            }
        });
        Btn_Col_Kuro_3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Btn_Col_Kuro_3ActionPerformed(evt);
            }
        });
        jPanel4.add(Btn_Col_Kuro_3, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 350, 100, 110));

        Btn_Col_Ghi_1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes_Ropa_Pequeño/Bu_Ghibli_P.jpg"))); // NOI18N
        Btn_Col_Ghi_1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Btn_Col_Ghi_1MouseClicked(evt);
            }
        });
        Btn_Col_Ghi_1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Btn_Col_Ghi_1ActionPerformed(evt);
            }
        });
        jPanel4.add(Btn_Col_Ghi_1, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 50, 100, 110));

        Btn_Col_Ghi_2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes_Ropa_Pequeño/Ca_Ghibli_P.jpg"))); // NOI18N
        Btn_Col_Ghi_2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Btn_Col_Ghi_2MouseClicked(evt);
            }
        });
        Btn_Col_Ghi_2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Btn_Col_Ghi_2ActionPerformed(evt);
            }
        });
        jPanel4.add(Btn_Col_Ghi_2, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 200, 100, 110));

        Btn_Col_Uzu_3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes_Ropa_Pequeño/Ca_Uzumaki_P2.jpg"))); // NOI18N
        Btn_Col_Uzu_3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Btn_Col_Uzu_3MouseClicked(evt);
            }
        });
        Btn_Col_Uzu_3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Btn_Col_Uzu_3ActionPerformed(evt);
            }
        });
        jPanel4.add(Btn_Col_Uzu_3, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 350, 100, 110));

        jLabel35.setFont(new java.awt.Font("Swis721 Hv BT", 2, 12)); // NOI18N
        jLabel35.setText("$45.000");
        jPanel4.add(jLabel35, new org.netbeans.lib.awtextra.AbsoluteConstraints(236, 330, 50, -1));

        jLabel43.setFont(new java.awt.Font("Swis721 Hv BT", 2, 12)); // NOI18N
        jLabel43.setText("$45.000");
        jPanel4.add(jLabel43, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 480, -1, -1));

        jLabel84.setFont(new java.awt.Font("Swis721 Hv BT", 2, 12)); // NOI18N
        jLabel84.setText("Camiseta Uzumaki Model 2");
        jPanel4.add(jLabel84, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 460, 170, -1));

        jLabel85.setFont(new java.awt.Font("Swis721 Hv BT", 2, 12)); // NOI18N
        jLabel85.setText("Camiseta Uzumaki Model 1");
        jPanel4.add(jLabel85, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 310, 170, -1));

        jLabel86.setFont(new java.awt.Font("Swis721 Hv BT", 2, 12)); // NOI18N
        jLabel86.setText("Buzo Ghibli");
        jPanel4.add(jLabel86, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 160, 80, -1));

        jLabel87.setFont(new java.awt.Font("Swis721 Hv BT", 2, 12)); // NOI18N
        jLabel87.setText("$80.000");
        jPanel4.add(jLabel87, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 180, 50, -1));

        jLabel88.setFont(new java.awt.Font("Swis721 Hv BT", 2, 12)); // NOI18N
        jLabel88.setText("Buzo Ghibli");
        jPanel4.add(jLabel88, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 310, 90, -1));

        jLabel89.setFont(new java.awt.Font("Swis721 Hv BT", 2, 12)); // NOI18N
        jLabel89.setText("$80.000");
        jPanel4.add(jLabel89, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 330, 50, 20));

        jLabel90.setFont(new java.awt.Font("Swis721 Hv BT", 2, 12)); // NOI18N
        jLabel90.setText("Buzo Kuromi");
        jPanel4.add(jLabel90, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 160, -1, -1));

        jLabel91.setFont(new java.awt.Font("Swis721 Hv BT", 2, 12)); // NOI18N
        jLabel91.setText("$80.000");
        jPanel4.add(jLabel91, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 180, 50, -1));

        jLabel92.setFont(new java.awt.Font("Swis721 Hv BT", 2, 12)); // NOI18N
        jLabel92.setText("Buzo Hora de Aventura ");
        jPanel4.add(jLabel92, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 310, 150, -1));

        jLabel93.setFont(new java.awt.Font("Swis721 Hv BT", 2, 12)); // NOI18N
        jLabel93.setText("$80.000");
        jPanel4.add(jLabel93, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 330, 50, -1));

        jLabel94.setFont(new java.awt.Font("Swis721 Hv BT", 2, 12)); // NOI18N
        jLabel94.setText("Camisa Hora de Aventura");
        jPanel4.add(jLabel94, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 460, 170, -1));

        jLabel95.setFont(new java.awt.Font("Swis721 Hv BT", 2, 12)); // NOI18N
        jLabel95.setText("$45.000");
        jPanel4.add(jLabel95, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 480, 90, -1));

        jLabel96.setFont(new java.awt.Font("Swis721 Hv BT", 2, 12)); // NOI18N
        jLabel96.setText("Medias Ghibli");
        jPanel4.add(jLabel96, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 460, 100, -1));

        jLabel97.setFont(new java.awt.Font("Swis721 Hv BT", 2, 12)); // NOI18N
        jLabel97.setText("$10.000");
        jPanel4.add(jLabel97, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 480, 50, -1));

        jLabel98.setFont(new java.awt.Font("Swis721 Hv BT", 2, 12)); // NOI18N
        jLabel98.setText("Medias Kuromi");
        jPanel4.add(jLabel98, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 460, 100, -1));

        jLabel99.setFont(new java.awt.Font("Swis721 Hv BT", 2, 12)); // NOI18N
        jLabel99.setText("$10.000");
        jPanel4.add(jLabel99, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 480, 50, -1));

        jLabel100.setFont(new java.awt.Font("Swis721 Hv BT", 2, 12)); // NOI18N
        jLabel100.setText("Buzo Uzumaki");
        jPanel4.add(jLabel100, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 610, 90, -1));

        jLabel101.setFont(new java.awt.Font("Swis721 Hv BT", 2, 12)); // NOI18N
        jLabel101.setText("$80.000");
        jPanel4.add(jLabel101, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 630, 50, -1));

        jLabel102.setFont(new java.awt.Font("Swis721 Hv BT", 2, 12)); // NOI18N
        jLabel102.setText("Medias Uzumaki");
        jPanel4.add(jLabel102, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 150, 110, 30));

        jLabel103.setFont(new java.awt.Font("Swis721 Hv BT", 2, 12)); // NOI18N
        jLabel103.setText("$10.000");
        jPanel4.add(jLabel103, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 170, 50, 30));

        jLabel104.setFont(new java.awt.Font("Swis721 Hv BT", 2, 12)); // NOI18N
        jLabel104.setText("Medias Hora de Aventura");
        jPanel4.add(jLabel104, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 160, 160, -1));

        jLabel105.setFont(new java.awt.Font("Swis721 Hv BT", 2, 12)); // NOI18N
        jLabel105.setText("$10.000");
        jPanel4.add(jLabel105, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 180, 50, -1));

        jLabel106.setFont(new java.awt.Font("Swis721 Hv BT", 2, 12)); // NOI18N
        jLabel106.setText("Camiseta Kuromi");
        jPanel4.add(jLabel106, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 310, 130, 20));

        jLabel107.setFont(new java.awt.Font("Swis721 Hv BT", 2, 12)); // NOI18N
        jLabel107.setText("$45.000");
        jPanel4.add(jLabel107, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 330, 50, 20));

        Panel_Colecciones.addTab("Colecciones", jPanel4);

        Escritorio.add(Panel_Colecciones, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 110, -1, -1));

        jPanel5.setBackground(new java.awt.Color(0, 204, 153));
        jPanel5.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setFont(new java.awt.Font("Swis721 Hv BT", 3, 12)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("ENVIOS GRATIS A TODO EL PAÍS POR COMPRAS SUPERIORES A $100.000 :)");
        jPanel5.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 0, -1, -1));

        Escritorio.add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 880, 20));

        jPanel6.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Btn_Carrito.setIcon(new javax.swing.ImageIcon(getClass().getResource("/FRONTEND_IMAGENESS/caroo (1).png"))); // NOI18N
        Btn_Carrito.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Btn_CarritoMouseClicked(evt);
            }
        });
        Btn_Carrito.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Btn_CarritoActionPerformed(evt);
            }
        });
        jPanel6.add(Btn_Carrito, new org.netbeans.lib.awtextra.AbsoluteConstraints(731, 37, 46, 36));

        jButton6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/FRONTEND_IMAGENESS/LUpita lupita (1).png"))); // NOI18N
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });
        jPanel6.add(jButton6, new org.netbeans.lib.awtextra.AbsoluteConstraints(144, 33, -1, -1));

        jLabel4.setBackground(new java.awt.Color(255, 255, 255));
        jLabel4.setFont(new java.awt.Font("Showcard Gothic", 0, 36)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 102, 102));
        jLabel4.setText("PETITE");
        jPanel6.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 30, -1, 60));

        textField1.setText("Buscar...");
        textField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textField1ActionPerformed(evt);
            }
        });
        jPanel6.add(textField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(225, 37, 442, -1));

        Escritorio.add(jPanel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 880, 80));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Escritorio)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Escritorio, javax.swing.GroupLayout.DEFAULT_SIZE, 761, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void Btn_CarritoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Btn_CarritoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Btn_CarritoActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton6ActionPerformed

    private void textField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textField1ActionPerformed

    private void vermasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_vermasActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_vermasActionPerformed

    private void jButton11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton11ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton11ActionPerformed

    private void Btn_Ropa_P2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Btn_Ropa_P2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Btn_Ropa_P2ActionPerformed

    private void Btn_Ropa_P1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Btn_Ropa_P1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Btn_Ropa_P1ActionPerformed

    private void Btn_Cat_Bu_3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Btn_Cat_Bu_3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Btn_Cat_Bu_3ActionPerformed

    private void Btn_Cat_Me_3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Btn_Cat_Me_3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Btn_Cat_Me_3ActionPerformed

    private void Btn_Cat_Bu_2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Btn_Cat_Bu_2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Btn_Cat_Bu_2ActionPerformed

    private void Btn_Cat_Bu_1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Btn_Cat_Bu_1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Btn_Cat_Bu_1ActionPerformed

    private void Btn_Cat_Pa_1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Btn_Cat_Pa_1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Btn_Cat_Pa_1ActionPerformed

    private void Btn_Cat_Pa_2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Btn_Cat_Pa_2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Btn_Cat_Pa_2ActionPerformed

    private void Btn_Cat_Ca_1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Btn_Cat_Ca_1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Btn_Cat_Ca_1ActionPerformed

    private void Btn_Cat_Ca_2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Btn_Cat_Ca_2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Btn_Cat_Ca_2ActionPerformed

    private void Btn_Cat_Ca_3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Btn_Cat_Ca_3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Btn_Cat_Ca_3ActionPerformed

    private void Btn_Cat_Me_1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Btn_Cat_Me_1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Btn_Cat_Me_1ActionPerformed

    private void Btn_Cat_Me_2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Btn_Cat_Me_2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Btn_Cat_Me_2ActionPerformed

    private void Btn_Cat_Pa_3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Btn_Cat_Pa_3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Btn_Cat_Pa_3ActionPerformed

    private void Btn_Cat_Bu_4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Btn_Cat_Bu_4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Btn_Cat_Bu_4ActionPerformed

    private void Btn_Cat_Ca_4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Btn_Cat_Ca_4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Btn_Cat_Ca_4ActionPerformed

    private void Btn_Cat_Me_4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Btn_Cat_Me_4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Btn_Cat_Me_4ActionPerformed

    private void Btn_Ropa_P1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Btn_Ropa_P1MouseClicked
        Prod verformulario=new Prod();
        verformulario.setVisible(true);
    }//GEN-LAST:event_Btn_Ropa_P1MouseClicked

    private void Btn_CarritoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Btn_CarritoMouseClicked
        Carrito verformulario=new Carrito();
        verformulario.setVisible(true);
        
    }//GEN-LAST:event_Btn_CarritoMouseClicked

    private void Btn_Ropa_P2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Btn_Ropa_P2MouseClicked
        Prod verformulario=new Prod();
        verformulario.setVisible(true);
    }//GEN-LAST:event_Btn_Ropa_P2MouseClicked

    private void BtnRopa_P3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BtnRopa_P3MouseClicked
        Prod verformulario=new Prod();
        verformulario.setVisible(true);
    }//GEN-LAST:event_BtnRopa_P3MouseClicked

    private void Btn_Cat_Bu_1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Btn_Cat_Bu_1MouseClicked
        Prod verformulario=new Prod();
        verformulario.setVisible(true);
    }//GEN-LAST:event_Btn_Cat_Bu_1MouseClicked

    private void Btn_Cat_Bu_2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Btn_Cat_Bu_2MouseClicked
        Prod verformulario=new Prod();
        verformulario.setVisible(true);
    }//GEN-LAST:event_Btn_Cat_Bu_2MouseClicked

    private void Btn_Cat_Bu_3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Btn_Cat_Bu_3MouseClicked
        Prod verformulario=new Prod();
        verformulario.setVisible(true);
    }//GEN-LAST:event_Btn_Cat_Bu_3MouseClicked

    private void Btn_Cat_Bu_4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Btn_Cat_Bu_4MouseClicked
        Prod verformulario=new Prod();
        verformulario.setVisible(true);
    }//GEN-LAST:event_Btn_Cat_Bu_4MouseClicked

    private void Btn_Cat_Pa_1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Btn_Cat_Pa_1MouseClicked
        Prod verformulario=new Prod();
        verformulario.setVisible(true);
    }//GEN-LAST:event_Btn_Cat_Pa_1MouseClicked

    private void Btn_Cat_Pa_2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Btn_Cat_Pa_2MouseClicked
        Prod verformulario=new Prod();
        verformulario.setVisible(true);
    }//GEN-LAST:event_Btn_Cat_Pa_2MouseClicked

    private void Btn_Cat_Pa_3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Btn_Cat_Pa_3MouseClicked
        Prod verformulario=new Prod();
        verformulario.setVisible(true);
    }//GEN-LAST:event_Btn_Cat_Pa_3MouseClicked

    private void Btn_Cat_Ca_1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Btn_Cat_Ca_1MouseClicked
        Prod verformulario=new Prod();
        verformulario.setVisible(true);
    }//GEN-LAST:event_Btn_Cat_Ca_1MouseClicked

    private void Btn_Cat_Ca_2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Btn_Cat_Ca_2MouseClicked
        Prod verformulario=new Prod();
        verformulario.setVisible(true);
    }//GEN-LAST:event_Btn_Cat_Ca_2MouseClicked

    private void Btn_Cat_Ca_3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Btn_Cat_Ca_3MouseClicked
        Prod verformulario=new Prod();
        verformulario.setVisible(true);
    }//GEN-LAST:event_Btn_Cat_Ca_3MouseClicked

    private void Btn_Cat_Ca_4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Btn_Cat_Ca_4MouseClicked
        Prod verformulario=new Prod();
        verformulario.setVisible(true);
    }//GEN-LAST:event_Btn_Cat_Ca_4MouseClicked

    private void Btn_Cat_Me_4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Btn_Cat_Me_4MouseClicked
        Prod verformulario=new Prod();
        verformulario.setVisible(true);
    }//GEN-LAST:event_Btn_Cat_Me_4MouseClicked

    private void Btn_Cat_Me_3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Btn_Cat_Me_3MouseClicked
        Prod verformulario=new Prod();
        verformulario.setVisible(true);
    }//GEN-LAST:event_Btn_Cat_Me_3MouseClicked

    private void Btn_Cat_Me_2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Btn_Cat_Me_2MouseClicked
        Prod verformulario=new Prod();
        verformulario.setVisible(true);
    }//GEN-LAST:event_Btn_Cat_Me_2MouseClicked

    private void Btn_Cat_Me_1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Btn_Cat_Me_1MouseClicked
        Prod verformulario=new Prod();
        verformulario.setVisible(true);
    }//GEN-LAST:event_Btn_Cat_Me_1MouseClicked

    private void Btn_Nove_5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Btn_Nove_5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Btn_Nove_5ActionPerformed

    private void Btn_Nove_5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Btn_Nove_5MouseClicked
        Prod verformulario=new Prod();
        verformulario.setVisible(true);
    }//GEN-LAST:event_Btn_Nove_5MouseClicked

    private void PantActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PantActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_PantActionPerformed

    private void PantMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_PantMouseClicked
        Prod verformulario=new Prod();
        verformulario.setVisible(true);
    }//GEN-LAST:event_PantMouseClicked

    private void Btn_Nove_6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Btn_Nove_6ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Btn_Nove_6ActionPerformed

    private void Btn_Nove_6MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Btn_Nove_6MouseClicked
        Prod verformulario=new Prod();
        verformulario.setVisible(true);
    }//GEN-LAST:event_Btn_Nove_6MouseClicked

    private void Btn_Nove_3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Btn_Nove_3MouseClicked
        Prod verformulario=new Prod();
        verformulario.setVisible(true);
    }//GEN-LAST:event_Btn_Nove_3MouseClicked

    private void Btn_Nove_2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Btn_Nove_2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Btn_Nove_2ActionPerformed

    private void Btn_Nove_2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Btn_Nove_2MouseClicked
        Prod verformulario=new Prod();
        verformulario.setVisible(true);
    }//GEN-LAST:event_Btn_Nove_2MouseClicked

    private void Btn_Nove_4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Btn_Nove_4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Btn_Nove_4ActionPerformed

    private void Btn_Nove_4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Btn_Nove_4MouseClicked
        Prod verformulario=new Prod();
        verformulario.setVisible(true);
    }//GEN-LAST:event_Btn_Nove_4MouseClicked

    private void Btn_Col_Uzu_3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Btn_Col_Uzu_3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Btn_Col_Uzu_3ActionPerformed

    private void Btn_Col_Uzu_3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Btn_Col_Uzu_3MouseClicked
        Prod verformulario=new Prod();
        verformulario.setVisible(true);
    }//GEN-LAST:event_Btn_Col_Uzu_3MouseClicked

    private void Btn_Col_Ghi_2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Btn_Col_Ghi_2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Btn_Col_Ghi_2ActionPerformed

    private void Btn_Col_Ghi_2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Btn_Col_Ghi_2MouseClicked
        Prod verformulario=new Prod();
        verformulario.setVisible(true);
    }//GEN-LAST:event_Btn_Col_Ghi_2MouseClicked

    private void Btn_Col_Ghi_1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Btn_Col_Ghi_1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Btn_Col_Ghi_1ActionPerformed

    private void Btn_Col_Ghi_1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Btn_Col_Ghi_1MouseClicked
        Prod verformulario=new Prod();
        verformulario.setVisible(true);
    }//GEN-LAST:event_Btn_Col_Ghi_1MouseClicked

    private void Btn_Col_Kuro_3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Btn_Col_Kuro_3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Btn_Col_Kuro_3ActionPerformed

    private void Btn_Col_Kuro_3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Btn_Col_Kuro_3MouseClicked
        Prod verformulario=new Prod();
        verformulario.setVisible(true);
    }//GEN-LAST:event_Btn_Col_Kuro_3MouseClicked

    private void Btn_Col_Kuro_2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Btn_Col_Kuro_2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Btn_Col_Kuro_2ActionPerformed

    private void Btn_Col_Kuro_2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Btn_Col_Kuro_2MouseClicked
        Prod verformulario=new Prod();
        verformulario.setVisible(true);
    }//GEN-LAST:event_Btn_Col_Kuro_2MouseClicked

    private void Btn_Col_Kuro_1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Btn_Col_Kuro_1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Btn_Col_Kuro_1ActionPerformed

    private void Btn_Col_Kuro_1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Btn_Col_Kuro_1MouseClicked
        Prod verformulario=new Prod();
        verformulario.setVisible(true);
    }//GEN-LAST:event_Btn_Col_Kuro_1MouseClicked

    private void Btn_Col_Uzu_4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Btn_Col_Uzu_4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Btn_Col_Uzu_4ActionPerformed

    private void Btn_Col_Uzu_4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Btn_Col_Uzu_4MouseClicked
        Prod verformulario=new Prod();
        verformulario.setVisible(true);
    }//GEN-LAST:event_Btn_Col_Uzu_4MouseClicked

    private void Btn_Col_Uzu_2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Btn_Col_Uzu_2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Btn_Col_Uzu_2ActionPerformed

    private void Btn_Col_Uzu_2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Btn_Col_Uzu_2MouseClicked
        Prod verformulario=new Prod();
        verformulario.setVisible(true);
    }//GEN-LAST:event_Btn_Col_Uzu_2MouseClicked

    private void Btn_Col_Uzu_1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Btn_Col_Uzu_1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Btn_Col_Uzu_1ActionPerformed

    private void Btn_Col_Uzu_1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Btn_Col_Uzu_1MouseClicked
        Prod verformulario=new Prod();
        verformulario.setVisible(true);
    }//GEN-LAST:event_Btn_Col_Uzu_1MouseClicked

    private void Btn_Col_HA_1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Btn_Col_HA_1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Btn_Col_HA_1ActionPerformed

    private void Btn_Col_HA_1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Btn_Col_HA_1MouseClicked
        Prod verformulario=new Prod();
        verformulario.setVisible(true);
    }//GEN-LAST:event_Btn_Col_HA_1MouseClicked

    private void Btn_Col_HA_2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Btn_Col_HA_2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Btn_Col_HA_2ActionPerformed

    private void Btn_Col_HA_2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Btn_Col_HA_2MouseClicked
        Prod verformulario=new Prod();
        verformulario.setVisible(true);
    }//GEN-LAST:event_Btn_Col_HA_2MouseClicked

    private void Btn_Col_Ghi_3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Btn_Col_Ghi_3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Btn_Col_Ghi_3ActionPerformed

    private void Btn_Col_Ghi_3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Btn_Col_Ghi_3MouseClicked
        Prod verformulario=new Prod();
        verformulario.setVisible(true);
    }//GEN-LAST:event_Btn_Col_Ghi_3MouseClicked

    private void Btn_Col_HA_3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Btn_Col_HA_3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Btn_Col_HA_3ActionPerformed

    private void Btn_Col_HA_3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Btn_Col_HA_3MouseClicked
        Prod verformulario=new Prod();
        verformulario.setVisible(true);
    }//GEN-LAST:event_Btn_Col_HA_3MouseClicked

    private void vermasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_vermasMouseClicked
        Prod verformulario=new Prod();
        verformulario.setVisible(true);
    }//GEN-LAST:event_vermasMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Principal_Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Principal_Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Principal_Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Principal_Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Principal_Menu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnRopa_P3;
    private javax.swing.JButton Btn_Carrito;
    private javax.swing.JButton Btn_Cat_Bu_1;
    private javax.swing.JButton Btn_Cat_Bu_2;
    private javax.swing.JButton Btn_Cat_Bu_3;
    private javax.swing.JButton Btn_Cat_Bu_4;
    private javax.swing.JButton Btn_Cat_Ca_1;
    private javax.swing.JButton Btn_Cat_Ca_2;
    private javax.swing.JButton Btn_Cat_Ca_3;
    private javax.swing.JButton Btn_Cat_Ca_4;
    private javax.swing.JButton Btn_Cat_Me_1;
    private javax.swing.JButton Btn_Cat_Me_2;
    private javax.swing.JButton Btn_Cat_Me_3;
    private javax.swing.JButton Btn_Cat_Me_4;
    private javax.swing.JButton Btn_Cat_Pa_1;
    private javax.swing.JButton Btn_Cat_Pa_2;
    private javax.swing.JButton Btn_Cat_Pa_3;
    private javax.swing.JButton Btn_Col_Ghi_1;
    private javax.swing.JButton Btn_Col_Ghi_2;
    private javax.swing.JButton Btn_Col_Ghi_3;
    private javax.swing.JButton Btn_Col_HA_1;
    private javax.swing.JButton Btn_Col_HA_2;
    private javax.swing.JButton Btn_Col_HA_3;
    private javax.swing.JButton Btn_Col_Kuro_1;
    private javax.swing.JButton Btn_Col_Kuro_2;
    private javax.swing.JButton Btn_Col_Kuro_3;
    private javax.swing.JButton Btn_Col_Uzu_1;
    private javax.swing.JButton Btn_Col_Uzu_2;
    private javax.swing.JButton Btn_Col_Uzu_3;
    private javax.swing.JButton Btn_Col_Uzu_4;
    private javax.swing.JButton Btn_Nove_2;
    private javax.swing.JButton Btn_Nove_3;
    private javax.swing.JButton Btn_Nove_4;
    private javax.swing.JButton Btn_Nove_5;
    private javax.swing.JButton Btn_Nove_6;
    private javax.swing.JButton Btn_Ropa_P1;
    private javax.swing.JButton Btn_Ropa_P2;
    private javax.swing.JDesktopPane Escritorio;
    private javax.swing.JTabbedPane Panel_Colecciones;
    private javax.swing.JButton Pant;
    private javax.swing.JDesktopPane desktopPane1;
    private javax.swing.JDesktopPane desktopPane2;
    private javax.swing.JButton jButton11;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel100;
    private javax.swing.JLabel jLabel101;
    private javax.swing.JLabel jLabel102;
    private javax.swing.JLabel jLabel103;
    private javax.swing.JLabel jLabel104;
    private javax.swing.JLabel jLabel105;
    private javax.swing.JLabel jLabel106;
    private javax.swing.JLabel jLabel107;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel43;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel50;
    private javax.swing.JLabel jLabel51;
    private javax.swing.JLabel jLabel52;
    private javax.swing.JLabel jLabel53;
    private javax.swing.JLabel jLabel54;
    private javax.swing.JLabel jLabel55;
    private javax.swing.JLabel jLabel56;
    private javax.swing.JLabel jLabel57;
    private javax.swing.JLabel jLabel58;
    private javax.swing.JLabel jLabel59;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel60;
    private javax.swing.JLabel jLabel61;
    private javax.swing.JLabel jLabel62;
    private javax.swing.JLabel jLabel63;
    private javax.swing.JLabel jLabel64;
    private javax.swing.JLabel jLabel65;
    private javax.swing.JLabel jLabel66;
    private javax.swing.JLabel jLabel67;
    private javax.swing.JLabel jLabel68;
    private javax.swing.JLabel jLabel69;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel70;
    private javax.swing.JLabel jLabel71;
    private javax.swing.JLabel jLabel72;
    private javax.swing.JLabel jLabel73;
    private javax.swing.JLabel jLabel74;
    private javax.swing.JLabel jLabel75;
    private javax.swing.JLabel jLabel76;
    private javax.swing.JLabel jLabel77;
    private javax.swing.JLabel jLabel78;
    private javax.swing.JLabel jLabel79;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel80;
    private javax.swing.JLabel jLabel81;
    private javax.swing.JLabel jLabel82;
    private javax.swing.JLabel jLabel83;
    private javax.swing.JLabel jLabel84;
    private javax.swing.JLabel jLabel85;
    private javax.swing.JLabel jLabel86;
    private javax.swing.JLabel jLabel87;
    private javax.swing.JLabel jLabel88;
    private javax.swing.JLabel jLabel89;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel jLabel90;
    private javax.swing.JLabel jLabel91;
    private javax.swing.JLabel jLabel92;
    private javax.swing.JLabel jLabel93;
    private javax.swing.JLabel jLabel94;
    private javax.swing.JLabel jLabel95;
    private javax.swing.JLabel jLabel96;
    private javax.swing.JLabel jLabel97;
    private javax.swing.JLabel jLabel98;
    private javax.swing.JLabel jLabel99;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel12;
    private javax.swing.JPanel jPanel13;
    private javax.swing.JPanel jPanel14;
    private javax.swing.JPanel jPanel15;
    private javax.swing.JPanel jPanel16;
    private javax.swing.JPanel jPanel17;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private java.awt.TextField textField1;
    private javax.swing.JButton vermas;
    // End of variables declaration//GEN-END:variables

}
