/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package FRONTEND_;

/**
 *
 * @author Usuario
 */
public class Prod extends javax.swing.JFrame {

    /**
     * Creates new form Prod
     */
    public Prod() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        desktopPane = new javax.swing.JDesktopPane();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jButton6 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        jButton8 = new javax.swing.JButton();
        jButton9 = new javax.swing.JButton();
        jButton10 = new javax.swing.JButton();
        jComboBox1 = new javax.swing.JComboBox<>();
        jButton11 = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jButton12 = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        desktopPane.setBackground(new java.awt.Color(255, 208, 208));
        desktopPane.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 204, 153)));

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes_Producto/Sueter_Prin_1 (1).png"))); // NOI18N
        jButton1.setToolTipText("");
        desktopPane.add(jButton1);
        jButton1.setBounds(180, 60, 220, 350);

        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes_Producto/Sueter_Prin_1 (2).png"))); // NOI18N
        desktopPane.add(jButton2);
        jButton2.setBounds(100, 60, 60, 70);

        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes_Producto/Sueter_Back_2.png"))); // NOI18N
        jButton3.setToolTipText("");
        desktopPane.add(jButton3);
        jButton3.setBounds(100, 140, 60, 70);

        jButton4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes_Producto/Sueter_Cuello_2.png"))); // NOI18N
        jButton4.setToolTipText("");
        desktopPane.add(jButton4);
        jButton4.setBounds(100, 300, 60, 70);

        jButton5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes_Producto/Sueter_Manga_2.png"))); // NOI18N
        jButton5.setToolTipText("");
        desktopPane.add(jButton5);
        jButton5.setBounds(100, 220, 60, 70);

        jLabel1.setFont(new java.awt.Font("Swis721 BT", 0, 12)); // NOI18N
        jLabel1.setText("Identificativo_del_producto");
        desktopPane.add(jLabel1);
        jLabel1.setBounds(460, 70, 170, 15);

        jLabel2.setFont(new java.awt.Font("Swis721 BT", 0, 12)); // NOI18N
        jLabel2.setText("Precio_del_producto");
        desktopPane.add(jLabel2);
        jLabel2.setBounds(460, 110, 120, 15);

        jButton6.setBackground(new java.awt.Color(255, 204, 153));
        jButton6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes_Producto/Verde.png"))); // NOI18N
        jButton6.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 204, 153)));
        desktopPane.add(jButton6);
        jButton6.setBounds(620, 150, 30, 30);

        jButton7.setBackground(new java.awt.Color(255, 204, 153));
        jButton7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes_Producto/Negro.png"))); // NOI18N
        jButton7.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 204, 153)));
        desktopPane.add(jButton7);
        jButton7.setBounds(460, 150, 30, 30);

        jButton8.setBackground(new java.awt.Color(255, 204, 153));
        jButton8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes_Producto/Blanco.png"))); // NOI18N
        jButton8.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 204, 153)));
        desktopPane.add(jButton8);
        jButton8.setBounds(500, 150, 30, 30);

        jButton9.setBackground(new java.awt.Color(255, 204, 153));
        jButton9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes_Producto/Rojo.png"))); // NOI18N
        jButton9.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 204, 153)));
        desktopPane.add(jButton9);
        jButton9.setBounds(540, 150, 30, 30);

        jButton10.setBackground(new java.awt.Color(255, 204, 153));
        jButton10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes_Producto/Azul.png"))); // NOI18N
        jButton10.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 204, 153)));
        desktopPane.add(jButton10);
        jButton10.setBounds(580, 150, 30, 30);

        jComboBox1.setBackground(new java.awt.Color(255, 208, 208));
        jComboBox1.setFont(new java.awt.Font("Swis721 BT", 0, 12)); // NOI18N
        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Tallas", "XS", "S", "M", "L", "XL", "XXL" }));
        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });
        desktopPane.add(jComboBox1);
        jComboBox1.setBounds(460, 200, 72, 21);

        jButton11.setBackground(new java.awt.Color(0, 0, 0));
        jButton11.setFont(new java.awt.Font("Swis721 BT", 0, 12)); // NOI18N
        jButton11.setForeground(new java.awt.Color(255, 255, 255));
        jButton11.setText("Añadir al Carrito");
        desktopPane.add(jButton11);
        jButton11.setBounds(460, 250, 200, 50);

        jPanel3.setBackground(new java.awt.Color(255, 204, 153));

        jButton12.setBackground(new java.awt.Color(255, 204, 153));
        jButton12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes_Producto/favorito.png"))); // NOI18N
        jButton12.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 204, 153)));

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(239, Short.MAX_VALUE)
                .addComponent(jButton12, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(21, 21, 21))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(191, Short.MAX_VALUE)
                .addComponent(jButton12, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(49, 49, 49))
        );

        desktopPane.add(jPanel3);
        jPanel3.setBounds(440, 60, 310, 290);

        jPanel1.setBackground(new java.awt.Color(255, 208, 208));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 820, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 490, Short.MAX_VALUE)
        );

        desktopPane.add(jPanel1);
        jPanel1.setBounds(0, 0, 820, 490);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(desktopPane, javax.swing.GroupLayout.DEFAULT_SIZE, 820, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(desktopPane, javax.swing.GroupLayout.PREFERRED_SIZE, 487, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Prod.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Prod.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Prod.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Prod.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Prod().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JDesktopPane desktopPane;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton10;
    private javax.swing.JButton jButton11;
    private javax.swing.JButton jButton12;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JButton jButton9;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    // End of variables declaration//GEN-END:variables
}
